// https://school.programmers.co.kr/learn/courses/30/lessons/12901
// 1,3,5,7,8,10,12
function solution(a, b) {
    let answer = '';
    switch(a) {
        case 1 :
        case 3 :
        case 5 :
        case 7 :
        case 8 :
        case 10 :
        case 12 : if(b < 32) {
            switch(b % 7) {
                
            }
        } 
        break;
        case 2 :
        break; 
        case 4,6,7,9,11:
        break;
        default:
    }
    
    return answer;
}

consoel.log(5,24) // "TUE"
